<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
     
    <PackageReference Include="Aspire.Hosting" Version="8.0.0-preview.*" />
   ## <PackageReference Include="Aspire.AppHost.Sdk" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IACSFWebApp\IACSFWebApp.csproj" />
    <ProjectReference Include="..\IACSFApp\IACSFApp.csproj" />
  </ItemGroup>

</Project>
